car/urls.py
from django.contrib import admin
from django.urls import path, include
from car import views

app_name="car"

urlpatterns = [
path('carwash/', views.carwashpageview.as_view()),
path('about/', views.aboutpageview.as_view()),
path('contact/', views.contactpageview.as_view()),
path('booking/', views.bookingpageview.as_view()),
path('feedback/', views.feedbackpageview.as_view()),
path('gallary/', views.gallarypageview.as_view()),
path('washing/', views.washingpageview.as_view()),
path('services/', views.servicespageview.as_view()),
path('Product/', views.product_list),

path('detailing/', views.detailingpageview.as_view()),

path('blog1/', views.blog1pageview.as_view()),

path('blog/', views.blogpageview.as_view()),
path('query/', views.querypageview.as_view()),

path('insert',views.insert),
path('insertfeedback',views.insertfeedback),
path('insertquery',views.insertquery),

path('insertbooking1',views.insertbooking1),
path('detail/', views.cartdetailview.as_view()),
path('cartdetail/', views.cartdetailview.as_view()),
path('payment/', views.paymentview.as_view()),

]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

carwash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
	path('',include('car.urls')),
	path('cart',include('cart.urls')),
	path('orders/',include('orders.urls')),
	path('paytm/',include('paytm.urls')),

	
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create')
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from car.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
	cart = Cart(request)  # create a new cart object passing it the request object
	product = get_object_or_404(Product, id=product_id) 
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
	return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
<style>
#image7 h1{ padding-top:60px; color:black; padding-left:90px; text-align:left;font-family:serif; font-style: italic; font-size:50px;}
</style>
<div class="row" id="head1">
<div class="parallax7" id="image7">
<div class="col-md-12">
<h1><b> My Shopping Cart</b></h1>

</div>
</div>
</div>

    <div class="container-fluid">
	<h2 style="text-align:center;font-family:serif; font-style: italic;color:#F5B900";><b></b></h2>
        <div class="row" style="margin-bottom: 10%">
        
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, Rs. {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color:#F5B900 ">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.photo %} {{ product.photo.url }} {% else %} 
									{% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; 
									width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action='{% url "cart:cart_add" product.id %}' method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-warning">
                                </form>
                            </td>
                            <td>
                                <a href='{% url "cart:cart_remove" product.id %}'>Remove</a>
                            </td>
                            <td>Rs. {{ item.price }}</td>
                            <td>Rs. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #F5B900">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>Rs. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-center">
            
            <a href="{% url "orders:order_create" %}" class="btn btn-warning">Checkout</a>
        </p>
        </div>
    </div>
	

{% endblock %}